// breedingGenetics.parity.test.ts
//
// Bit-for-bit parity between this file's TypeScript port and the on-chain
// Solidity source of truth (contracts/src/GeneticsLib.sol). Both fixture
// files below are GENERATED BY FORGE, never hand-written or generated from
// this TS implementation:
//
//   - contracts/test-vectors.json         (contracts/test/GenerateTestVectors.t.sol)
//   - contracts/test-vectors-fresh.json   (contracts/test/GenerateFreshTestVectors.t.sol)
//
// The second fixture uses a deliberately different token-ID range, gene
// formula, breedNonce stride, and entropy salt than the first (see that
// generator's header comment) specifically so a TS port that was
// overfit/hardcoded to the primary fixture's numbers - rather than an
// actual re-implementation of GeneticsLib's arithmetic - still gets caught.
//
// Regenerate both via `cd ../contracts && forge test` (writes both JSON
// files as a side effect of two `forge test` assertions, not a separate
// script). If a mismatch ever shows up here, the fix is ALWAYS on the TS
// side - never regenerate the vectors from this TS implementation, that
// would defeat the entire point of an independent ground truth.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import {
  breedingSeed,
  breedGenome,
  resolveGenome,
  inheritLocus,
  locusSeedFor,
  assertGenome,
  GENE_SLOTS,
  type Genome,
} from "./breedingGenetics";

const dirname = path.dirname(fileURLToPath(import.meta.url));

interface Vector {
  fatherTokenId: number;
  motherTokenId: number;
  breedNonce: number;
  entropy: string;
  fatherGenes: number[];
  motherGenes: number[];
  expectedSeed: string;
  expectedGenome: number[];
}

function loadVectors(filename: string): Vector[] {
  const p = path.resolve(dirname, "../contracts", filename);
  const raw = readFileSync(p, "utf-8");
  const vectors = JSON.parse(raw) as Vector[];
  if (!Array.isArray(vectors) || vectors.length === 0) {
    throw new Error(`${filename} loaded but contains no vectors`);
  }
  return vectors;
}

function runParitySuite(label: string, filename: string, minCount: number) {
  describe(`${label} (${filename})`, () => {
    const vectors = loadVectors(filename);

    it(`loads at least ${minCount} vectors`, () => {
      expect(vectors.length).toBeGreaterThanOrEqual(minCount);
    });

    it("matches expectedSeed and expectedGenome for every vector", () => {
      let checked = 0;
      for (const v of vectors) {
        const seed = breedingSeed(
          v.fatherTokenId,
          v.motherTokenId,
          v.breedNonce,
          v.entropy,
        );
        expect(seed.toString()).toBe(v.expectedSeed);

        const genome = resolveGenome(v.fatherGenes, v.motherGenes, seed);
        expect([...genome]).toEqual(v.expectedGenome);

        checked++;
      }
      expect(checked).toBe(vectors.length);
    });

    it("breedGenome() wrapper matches the same vectors end to end", () => {
      for (const v of vectors) {
        const { seed, genome } = breedGenome(
          v.fatherTokenId,
          v.motherTokenId,
          v.breedNonce,
          v.entropy,
          v.fatherGenes,
          v.motherGenes,
        );
        expect(seed.toString()).toBe(v.expectedSeed);
        expect([...genome]).toEqual(v.expectedGenome);
      }
    });
  });
}

// Primary fixture: >= 500 vectors per spec.
runParitySuite("primary fixture", "test-vectors.json", 500);

// Secondary, independently-formulated fixture: >= 100 vectors per spec.
// Combined with the primary fixture this exceeds the 600+ combined floor.
runParitySuite("fresh/staleness-guard fixture", "test-vectors-fresh.json", 100);

describe("combined vector coverage", () => {
  it("primary + fresh fixtures together cover 600+ vectors", () => {
    const primary = loadVectors("test-vectors.json");
    const fresh = loadVectors("test-vectors-fresh.json");
    expect(primary.length + fresh.length).toBeGreaterThanOrEqual(600);
  });
});

describe("byte-level API surface", () => {
  it("resolveGenome always returns exactly GENE_SLOTS values", () => {
    const father = [1, 2, 3, 4, 5];
    const mother = [250, 251, 252, 253, 254];
    const seed = breedingSeed(1, 2, 0, `0x${"ab".repeat(32)}`);
    const genome: Genome = resolveGenome(father, mother, seed);
    expect(genome.length).toBe(GENE_SLOTS);
    genome.forEach((g) => {
      expect(Number.isInteger(g)).toBe(true);
      expect(g).toBeGreaterThanOrEqual(0);
      expect(g).toBeLessThanOrEqual(255);
    });
  });

  it("is deterministic: same inputs always produce the same seed and genome", () => {
    const entropy = `0x${"cd".repeat(32)}`;
    const seedA = breedingSeed(42, 7, 3, entropy);
    const seedB = breedingSeed(42, 7, 3, entropy);
    expect(seedA).toBe(seedB);

    const genomeA = resolveGenome([1, 2, 3, 4, 5], [6, 7, 8, 9, 10], seedA);
    const genomeB = resolveGenome([1, 2, 3, 4, 5], [6, 7, 8, 9, 10], seedB);
    expect(genomeA).toEqual(genomeB);
  });

  it("different breedNonce changes the seed (entropy held constant)", () => {
    const entropy = `0x${"ef".repeat(32)}`;
    const seedA = breedingSeed(1, 2, 0, entropy);
    const seedB = breedingSeed(1, 2, 1, entropy);
    expect(seedA).not.toBe(seedB);
  });

  it("different entropy changes the seed (breedNonce held constant) - the whole point of the commit/reveal fix", () => {
    const seedA = breedingSeed(1, 2, 3, `0x${"01".repeat(32)}`);
    const seedB = breedingSeed(1, 2, 3, `0x${"02".repeat(32)}`);
    expect(seedA).not.toBe(seedB);
  });

  it("inheritLocus never returns an out-of-uint8-range value across a wide offset sweep", () => {
    const seed = breedingSeed(9, 99, 999, `0x${"11".repeat(32)}`);
    for (let offset = 0; offset < 64; offset++) {
      const val = inheritLocus(10, 240, seed, offset);
      expect(Number.isInteger(val)).toBe(true);
      expect(val).toBeGreaterThanOrEqual(0);
      expect(val).toBeLessThanOrEqual(255);
    }
  });

  it("locusSeedFor is the raw per-locus hash inheritLocus derives its decision from", () => {
    const seed = breedingSeed(1, 1, 1, `0x${"33".repeat(32)}`);
    const ls = locusSeedFor(seed, 0n);
    expect(typeof ls).toBe("bigint");
    expect(ls).toBeGreaterThanOrEqual(0n);
  });

  it("assertGenome rejects a wrong-length array", () => {
    expect(() => assertGenome([1, 2, 3])).toThrow();
  });

  it("assertGenome rejects out-of-range uint8 values", () => {
    expect(() => assertGenome([1, 2, 3, 4, 256])).toThrow();
    expect(() => assertGenome([1, 2, 3, 4, -1])).toThrow();
  });

  it("breedingSeed rejects a malformed entropy value", () => {
    expect(() => breedingSeed(1, 2, 3, "not-a-hash")).toThrow();
    expect(() => breedingSeed(1, 2, 3, "0x1234")).toThrow();
  });
});
