#!/bin/bash
# Hydrate h00dchan .env.local from macOS Keychain.
# Run this once per machine, or after Keychain changes.
# The generated .env.local is gitignored — never commit it.

set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env.local"
ACCOUNT="openclaw"

get_key() {
  local service="$1"
  security find-generic-password -a "$ACCOUNT" -s "$service" -w 2>/dev/null || echo ""
}

echo "Hydrating h00dchan secrets from Keychain..."

# Reown Project ID is public by design (client-bundled, domain-restricted
# via the Reown dashboard rather than kept confidential) - stored in
# Keychain anyway for a single source of truth, same as every other config
# value in this repo family, even though NEXT_PUBLIC_ exposure here isn't
# the credentials.md billing-key concern.
REOWN_PROJECT_ID=$(get_key "reown-project-id-h00dchan")

# Same Venice key ARI_ONE already uses (account: openclaw, service:
# venice-api-key) - not project-scoped, Venice keys aren't domain-restricted
# so one key works everywhere.
VENICE_API_KEY=$(get_key "venice-api-key")

# Shared secret the AI-generation trigger route checks before letting
# anything (a cron job, or you manually) fire off Venice-backed posts -
# without this, the route would be a public, unauthenticated way to spend
# your Venice API credits.
H00DCHAN_CRON_SECRET=$(get_key "h00dchan-cron-secret")

# Pinata dedicated gateway access token (coffee-collective-muskox-308,
# gateway ID 6c86ebb5-3e05-426d-b508-1c01904bb891 on the paid Pinata
# account). NEXT_PUBLIC_ on purpose: Pinata's own docs describe attaching
# this exact token to public gateway URLs as the intended usage pattern
# (it's a low-privilege gateway-read token, not the account JWT/API keys -
# leaking it risks quota abuse, not account compromise), and it needs to be
# in client-bundled <img src> URLs for the token grid/post images, not just
# server-side metadata fetches.
PINATA_GATEWAY_TOKEN=$(get_key "pinata-gateway-token-h00dchan")

# Same key the game projects already use (account: openclaw, service:
# alchemy-api-key) - not project-scoped, one key works across apps. Powers
# the token-bound-wallet explorer (lib/alchemy.ts): enhanced NFT/token
# balance APIs on Robinhood Chain, confirmed working live before wiring
# this up. Server-side only, no NEXT_PUBLIC_ prefix - the explorer page is
# a server component, never a client-side fetch.
ALCHEMY_API_KEY=$(get_key "alchemy-api-key")

# Ad-rental feature (lib/opensea.ts, lib/adPayment.ts) - both new, both
# required before that feature can actually accept a submission. Neither
# has a safe default: OPENSEA_API_KEY gates collection lookups, and without
# a real AD_TREASURY_ADDRESS every payment verification fails closed (see
# lib/adConfig.ts's own comment on why this one is NEXT_PUBLIC_ - it's a
# receiving address, not a secret, but it lives in Keychain anyway for one
# source of truth like everything else here).
OPENSEA_API_KEY=$(get_key "opensea-api-key-h00dchan")
AD_TREASURY_ADDRESS=$(get_key "ad-treasury-address-h00dchan")

# onlyChans image generation (lib/onlychansImage.ts) - same shared key the
# game projects already use (account: openclaw, service: openai-api-key),
# not project-scoped.
OPENAI_API_KEY=$(get_key "openai-api-key")

if [ -z "$REOWN_PROJECT_ID" ]; then
  echo "WARNING: reown-project-id-h00dchan not found in Keychain (account: $ACCOUNT)"
  echo "  Add it: security add-generic-password -a openclaw -s reown-project-id-h00dchan -w '<id>' -U"
fi

if [ -z "$VENICE_API_KEY" ]; then
  echo "WARNING: venice-api-key not found in Keychain (account: $ACCOUNT)"
fi

if [ -z "$OPENSEA_API_KEY" ]; then
  echo "WARNING: opensea-api-key-h00dchan not found - ad rental collection lookups will fail"
  echo "  Add it: security add-generic-password -a openclaw -s opensea-api-key-h00dchan -w '<key>' -U"
fi

if [ -z "$AD_TREASURY_ADDRESS" ]; then
  echo "WARNING: ad-treasury-address-h00dchan not found - ad rental payments will fail verification"
  echo "  Add it: security add-generic-password -a openclaw -s ad-treasury-address-h00dchan -w '<0x address>' -U"
fi

if [ -z "$OPENAI_API_KEY" ]; then
  echo "WARNING: openai-api-key not found - onlyChans generation will fail"
fi

# Write .env.local (chmod 600 — readable only by owner)
cat > "$ENV_FILE" <<EOF
# h00dchan environment — generated by scripts/hydrate-secrets.sh
# DO NOT COMMIT THIS FILE

NEXT_PUBLIC_REOWN_PROJECT_ID=${REOWN_PROJECT_ID}
VENICE_API_KEY=${VENICE_API_KEY}
H00DCHAN_CRON_SECRET=${H00DCHAN_CRON_SECRET}
NEXT_PUBLIC_PINATA_GATEWAY_DOMAIN=coffee-collective-muskox-308.mypinata.cloud
NEXT_PUBLIC_PINATA_GATEWAY_TOKEN=${PINATA_GATEWAY_TOKEN}
ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
OPENSEA_API_KEY=${OPENSEA_API_KEY}
NEXT_PUBLIC_AD_TREASURY_ADDRESS=${AD_TREASURY_ADDRESS}
OPENAI_API_KEY=${OPENAI_API_KEY}

# KV_REST_API_URL / KV_REST_API_TOKEN intentionally left unset here - no
# Upstash/Vercel KV project is provisioned yet. lib/store.ts falls back to
# an in-memory store when these are absent (see its own comment). Once a
# Vercel KV integration is attached at deploy time, those env vars are
# injected automatically - nothing in this script needs to change.
EOF

chmod 600 "$ENV_FILE"
echo "Done — .env.local written to $ENV_FILE"
echo "  NEXT_PUBLIC_REOWN_PROJECT_ID: $([ -n "$REOWN_PROJECT_ID" ] && echo "set" || echo "MISSING")"
echo "  VENICE_API_KEY: $([ -n "$VENICE_API_KEY" ] && echo "set" || echo "MISSING")"
