// Re-extracts the ABI arrays from forge's compiled build output
// (contracts/out/**/*.json) into typed, importable TS modules under
// lib/abi/ - the ONLY place any ABI may live in this app. Every reader/tx
// builder in lib/breedingController.ts and lib/babies.ts imports from
// here, never a hand-written inline ABI array - see BUG 4 in the design
// spec: an earlier attempt hand-wrote ABIs from guessed function names
// (breedWithChan/breedWithEth, setSirePrice, allListedTokenIds()...) that
// didn't exist on the real contracts. Generating straight from forge's own
// build output makes that class of bug structurally impossible: the
// wrapper functions either match the real ABI or fail to compile.
//
// Run with: npx tsx scripts/copy-abis.ts (or `npm run copy-abis`)
// Requires `forge build` to have already populated contracts/out/ (see
// contracts/README.md) - this script only copies, it never compiles.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_OUT = join(__dirname, "../contracts/out");
const ABI_OUT = join(__dirname, "../lib/abi");

const TARGETS: Array<{ contract: string; file: string; varName: string }> = [
  {
    contract: "BreedingController",
    file: "BreedingController.sol/BreedingController.json",
    varName: "BreedingControllerAbi",
  },
  {
    contract: "HoodchanGirlfriends",
    file: "HoodchanGirlfriends.sol/HoodchanGirlfriends.json",
    varName: "HoodchanGirlfriendsAbi",
  },
  {
    contract: "HoodchanBabies",
    file: "HoodchanBabies.sol/HoodchanBabies.json",
    varName: "HoodchanBabiesAbi",
  },
];

mkdirSync(ABI_OUT, { recursive: true });

for (const { contract, file, varName } of TARGETS) {
  const artifactPath = join(CONTRACTS_OUT, file);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  const outPath = join(ABI_OUT, `${contract}.ts`);
  const contents =
    `// AUTO-GENERATED by scripts/copy-abis.ts - do not hand-edit.\n` +
    `// Source of truth: contracts/out/${file} (forge build output).\n` +
    `// Re-run \`npm run copy-abis\` after any contracts/src/*.sol change +\n` +
    `// \`forge build\` to keep this in sync - never hand-write an ABI here.\n\n` +
    `export const ${varName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(outPath, contents);
  console.log(`Wrote ${outPath} (${artifact.abi.length} ABI entries)`);
}
